# Basic
title: Will's Home
subtitle: 一生温暖纯良，不舍爱与自由
welcome_message: 这辈子我干什么都可以，就是不能做一个一无所能，就能明辨是非的人。
description: 嗨，我是王丰(@willwangfeng),一名Java开发者
creator: <a href="http://onev.cat">@onevcat</a>

url: "http://vno.onevcat.com"

permalink: /:year/:month/:title/

# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: red

# The blog button should not be removed.
blog_button:
    title: Blog
    description: Visit blog

# Navigation buttons in the front page.
nav:
    # - {title: Projects, description: My Projects, url: 'http://project.onevcat.com'}
    # - {title: Another Button, description: A button, url: 'http://example.com'}

# Pagination
plugins: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    disqus: willwangfeng
    # duoshuo:

# Social
social:
    weibo: wfbupt
    github: willwangfeng
    twitter: willwangfeng
    mail: will.wangfeng@gmail.com

# Google Analytics
ga:
    # id: your_ga_id
    # host: your_host
